version: "3"

tasks:
  default:
    silent: true
    cmds:
      - $DOTFILES_ROOT/roles/zsh/src/bin/ubi --list-all

  help:
    silent: true
    cmds:
      - $DOTFILES_ROOT/roles/zsh/src/bin/ubi --list-all

  dotfiles:docker-dir:
    silent: true
    cmds:
      - echo "$DOTFILES_ROOT/roles/docker/src"

  dotfiles:edit:
    silent: true
    cmds:
      - code "$DOTFILES_ROOT"

  git:fix-commit-metadata:
    silent: true
    cmds:
      - git commit --amend --author='Yordis Prieto <yordis.prieto@gmail.com>' --date="$(date)"

  dotfiles:dc:
    silent: true
    aliases:
      - dc
    cmds:
      - >-
        docker compose
        --project-directory "$DOTFILES_ROOT/roles/docker/src"
        --file "$DOTFILES_ROOT/roles/docker/src/docker-compose.yml"
        {{.CLI_ARGS}}
