export PATH="/usr/local/opt/libxml2/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/.dotfiles/bin:$PATH"
export GOPATH="$HOME/Developer/GoLang"
export PATH="$GOPATH/bin:$PATH"
export PATH="$DOTFILES_ROOT_ZSH_ROOT/bin/private:$PATH"
export PATH="$DOTFILES_ROOT_ZSH_ROOT/bin:$PATH"
[[ -d "$HOME/.mix/escripts" ]] && export PATH="$HOME/.mix/escripts:$PATH"
[[ -d "$HOME/.cargo/bin" ]] && export PATH="$HOME/.cargo/bin:$PATH"

