- name: add Terraform Docs plugin to asdf
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf plugin-add terraform-docs https://github.com/looztra/asdf-terraform-docs"
    creates: "{{ user_home_directory }}/.asdf/plugins/terraform-docs/bin/install"
  register: terraform_docs_add
  failed_when: terraform_docs_add == 2

- name: install Terraform Docs versions
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf install terraform-docs {{ item }}"
    creates: "{{ user_home_directory }}/.asdf/installs/terraform-docs/{{ item }}/bin/terraform-docs"
  loop: "{{ versions }}"

- name: check if global Terraform Docs version is v{{ global_version }}
  shell: "{{ user_home_directory }}/.asdf/bin/asdf current terraform-docs | grep {{ global_version }}"
  register: terraform_docs_global_version
  changed_when: no
  ignore_errors: yes

- name: set global version for Terraform Docs to v{{ global_version }}
  command: "{{ user_home_directory }}/.asdf/bin/asdf global terraform-docs {{ global_version }}"
  when: terraform_docs_global_version.rc > 0
