- name: install emacs
  community.general.homebrew_cask:
    name: emacs
    state: latest

- name: link global .emacs file
  file:
    src: "{{ dotfiles_directory }}/roles/emacs/files/emacs.symlink"
    dest: "{{ user_home_directory }}/.emacs"
    state: link
